### ISSUE TITLE
Warning is not a defined constant

### ISSUE THREAD

**Issue by grantemsley** [Distinqt/ZTIDellBIOSSettings#2]
The iPrep variable gets set to Warning, Success or Failure.

In ZTIUtility.vbs (at least from MDT2013), Success and Failure are defined constants, but Warning is not.  This causes the script to fail because of the undefined variable, even for problems it would normally be able to continue.

Adding "Public Const Warning = 2" should fix it.

**Comment by NinoFloris** [comment]
Hi Grant,

Nice catch. This problem has been introduced since dfd2f9a26c (I did not have proper access to a dell machine back then) and has been lingering ever since, we have always had an optimal running environment it seems.
I have committed the fix, iPrep's warning state is never exposed so I just keep a local variable.

I will keep this scenario in mind when testing next time.
